---
apiVersion: v1
kind: Namespace
metadata:
  name: sample
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: sample
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 2
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: "gcr.io/google-samples/hello-app:2.0"
--- 
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: sample
  labels:
    app: hello
spec:
  type: ClusterIP
  selector:
    app: hello
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
--- 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: sample
spec:
  rules:
  - host: sample.firasbouw.nl
    http:
      paths:
      - backend:
          serviceName: hello-service
          servicePort: 80
